version: "3.0"
services:
    runner:
        image: gitlab/gitlab-runner:latest
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - booking-runner-config:/etc/gitlab-runner
volumes:
    booking-runner-config: