---

# - name: Ansible HealthCheck
#   hosts: vms
#   remote_user: "{{ default_remote_user }}"     # Specify your own username here
#   tasks:
#     - name: Run echo hello world
#       shell: echo 'Hello' from `hostname`
#       register: output
#     - debug: var=output.stdout_lines

- name: Install Gitlab and deploy Runner
  hosts: docker_swarm_manager
  remote_user: "{{ default_remote_user }}"
  roles:
    - gitlab                # Calls tasks from roles/gitlab/tasks
  vars:
    default_remote_user: obadia_r
    gitlab_ip: "{{ hostvars['manager'].ansible_host }}"
  